name: Heroku Build Logs
on: deployment_status

jobs:
  heroku-build-logs:
    name: Heroku Build Logs
    runs-on: ubuntu-latest
    steps:
      - name: Heroku Build Logs
        uses: mheap/github-action-heroku-logs@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEROKU_AUTH_TOKEN: ${{ secrets.HEROKU_AUTH_TOKEN }}
